Added nvim install

diff --git a/bin/dotfiles b/bin/dotfiles
--- a/bin/dotfiles
+++ b/bin/dotfiles
@@ -26,7 +26,7 @@ while [ $# -gt 0 ]; do
             ;;
         *)
             printf "Unknown option $1\n$0 --help for usage\n"
-            exit 1
+            FAILED_TASKS="$FAILED_TASKS:$TASK_NAME"; exit 1
             ;;
     esac
 done
@@ -85,11 +85,13 @@ START_TIME=$(date +%s)
 SKIP_AUTH=${SKIP_AUTH:-false}
 DEBUG_MODE=${DEBUG_MODE:-false}
 if $DEBUG_MODE; then pprint_warning "${yellow}Debug mode enabled${rf}"; fi
+SKIPPED_TASKS=""
+FAILED_TASKS=""
 
 PROCESSOR_ARCHITECTURE=$(uname -m | tr '[:upper:]' '[:lower:]' || echo "unknown")
-case "$PROCESSOR_ARCHITECTURE" in x86_64) ARCH="amd64";; arm64) ARCH="arm64";; *) echo "Unknown processor architecture" && exit 1;; esac
+case "$PROCESSOR_ARCHITECTURE" in x86_64) ARCH="amd64";; arm64) ARCH="arm64";; *) pprint_error "Unknown processor architecture" && FAILED_TASKS="$FAILED_TASKS:$TASK_NAME"; exit 1;; esac
 OPERATING_SYSTEM=$(uname -o | tr '[:upper:]' '[:lower:]' || echo "unknown")
-case "$OPERATING_SYSTEM" in *linux*) OS="linux";; *darwin*) OS="darwin";; *) echo "Unknown operating system" && exit 1;; esac
+case "$OPERATING_SYSTEM" in *linux*) OS="linux";; *darwin*) OS="darwin";; *) pprint_error "Unknown operating system" && FAILED_TASKS="$FAILED_TASKS:$TASK_NAME"; exit 1;; esac
 LINUX_DISTRO=$(awk -F'=' '/^ID=/ { gsub("\"","",$2); print tolower($2) }' /etc/*-release 2> /dev/null || echo "unknown")
 RUNNING_USER=$(whoami)
 SSH_DIR="$HOME/.ssh"
@@ -118,14 +120,17 @@ cleanup() {
     END_TIME=$(date +%s)
     ELAPSED_TIME=$(($END_TIME - $START_TIME))
     ELAPESED_TIME_FORMATTED=$(printf '%dh:%dm:%ds\n' $(($ELAPSED_TIME/3600)) $(($ELAPSED_TIME%3600/60)) $(($ELAPSED_TIME%60)))
-    
+    SKIPPED_TASKS=$(echo "$SKIPPED_TASKS" | sed 's/^://')
+    FAILED_TASKS=$(echo "$FAILED_TASKS" | sed 's/^://')
     rm -f "$TMP_LOG_FILE"
     
-    if [ $exit_code -eq 0 ]
-    then
-        pprint "Cleaned up"
+    if [ $exit_code -eq 0 ]; then
+        if [ ! -z "$SKIPPED_TASKS" ]; then
+            pprint_skip "Skipped tasks: ${cyan}$(IFS=:; for task in $SKIPPED_TASKS; do printf "$task "; done)${rf}"
+        fi
+        pprint "Finished successfully took ${purple}$ELAPESED_TIME_FORMATTED${rf}"
     else
-        pprint_error "Cleaned up and exit with code $exit_code"
+        pprint_error "Exit with failed tasks: ${red}$(IFS=:; for task in $FAILED_TASKS; do printf "$task "; done)${rf}"
     fi
     exit $exit_code
 }
@@ -156,7 +161,7 @@ if [ ! -d "$XDG_CONFIG_HOME" ]; then
     pprint_warning "Directory $XDG_CONFIG_HOME not found"
     pprint "Creating directory $XDG_CONFIG_HOME..."
     mkdir -p "$XDG_CONFIG_HOME" > $TMP_LOG_FILE 2>&1
-    if [ $? -ne 0 ]; then pprint_error "Failed to create directory $XDG_CONFIG_HOME"; pprint_error_info "$(cat $TMP_LOG_FILE)"; exit 1; fi
+    if [ $? -ne 0 ]; then pprint_error "Failed to create directory $XDG_CONFIG_HOME"; pprint_error_info "$(cat $TMP_LOG_FILE)"; FAILED_TASKS="$FAILED_TASKS:$TASK_NAME"; exit 1; fi
     pprint_check "Created directory ${green}$XDG_CONFIG_HOME${rf}"
 else
     pprint "Directory $XDG_CONFIG_HOME found"
@@ -168,32 +173,32 @@ install_with_package_manager() {
         *linux*)
             case "$LINUX_DISTRO" in
                 *ubuntu*|*debian*)
-                    $SUDO apt-get -y install "$1" > $TMP_LOG_FILE 2>&1; if [ $? -ne 0 ]; then pprint_error "Failed to install $1"; pprint_error_info "$(cat $TMP_LOG_FILE)"; exit 1; fi
+                    $SUDO apt update > /dev/null 2>&1 && apt-get -y install "$1" > $TMP_LOG_FILE 2>&1; if [ $? -ne 0 ]; then pprint_error "Failed to install $1"; pprint_error_info "$(cat $TMP_LOG_FILE)"; FAILED_TASKS="$FAILED_TASKS:$TASK_NAME"; exit 1; fi
                     ;;
                 *arch*)
-                    $SUDO pacman -S "$1" --noconfirm > $TMP_LOG_FILE 2>&1; if [ $? -ne 0 ]; then pprint_error "Failed to install $1"; pprint_error_info "$(cat $TMP_LOG_FILE)"; exit 1; fi
+                    $SUDO padman -Sy > /dev/null 2>&1 && pacman -S "$1" --noconfirm > $TMP_LOG_FILE 2>&1; if [ $? -ne 0 ]; then pprint_error "Failed to install $1"; pprint_error_info "$(cat $TMP_LOG_FILE)"; FAILED_TASKS="$FAILED_TASKS:$TASK_NAME"; exit 1; fi
                     ;;
                 *fedora*)
-                    $SUDO dnf -y install "$1" > $TMP_LOG_FILE 2>&1; if [ $? -ne 0 ]; then pprint_error "Failed to install $1"; pprint_error_info "$(cat $TMP_LOG_FILE)"; exit 1; fi
+                    $SUDO dnf -y install "$1" > $TMP_LOG_FILE 2>&1; if [ $? -ne 0 ]; then pprint_error "Failed to install $1"; pprint_error_info "$(cat $TMP_LOG_FILE)"; FAILED_TASKS="$FAILED_TASKS:$TASK_NAME"; exit 1; fi
                     ;;
                 *centos*)
-                    $SUDO yum -y install "$1" > $TMP_LOG_FILE 2>&1; if [ $? -ne 0 ]; then pprint_error "Failed to install $1"; pprint_error_info "$(cat $TMP_LOG_FILE)"; exit 1; fi
+                    $SUDO yum -y install "$1" > $TMP_LOG_FILE 2>&1; if [ $? -ne 0 ]; then pprint_error "Failed to install $1"; pprint_error_info "$(cat $TMP_LOG_FILE)"; FAILED_TASKS="$FAILED_TASKS:$TASK_NAME"; exit 1; fi
                     ;;
                 *alpine*)
-                    $SUDO apk add "$1" > $TMP_LOG_FILE 2>&1; if [ $? -ne 0 ]; then pprint_error "Failed to install $1"; pprint_error_info "$(cat $TMP_LOG_FILE)"; exit 1; fi
+                    $SUDO apk add "$1" --update > $TMP_LOG_FILE 2>&1; if [ $? -ne 0 ]; then pprint_error "Failed to install $1"; pprint_error_info "$(cat $TMP_LOG_FILE)"; FAILED_TASKS="$FAILED_TASKS:$TASK_NAME"; exit 1; fi
                     ;;
                 *)
                     pprint "${red}Unknown Linux distribution${rf}"
-                    exit 1
+                    FAILED_TASKS="$FAILED_TASKS:$TASK_NAME"; exit 1
                     ;;
             esac
             ;;
         *darwin*)
-            brew install "$1" > $TMP_LOG_FILE 2>&1; if [ $? -ne 0 ]; then pprint_error "Failed to install $1"; pprint_error_info "$(cat $TMP_LOG_FILE)"; exit 1; fi
+            brew install "$1" > $TMP_LOG_FILE 2>&1; if [ $? -ne 0 ]; then pprint_error "Failed to install $1"; pprint_error_info "$(cat $TMP_LOG_FILE)"; FAILED_TASKS="$FAILED_TASKS:$TASK_NAME"; exit 1; fi
             ;;
         *)
             pprint "${red}Unknown operating system${rf}"
-            exit 1
+            FAILED_TASKS="$FAILED_TASKS:$TASK_NAME"; exit 1
             ;;
     esac
 }
@@ -217,7 +222,7 @@ case "$OPERATING_SYSTEM" in
             pprint_warning "${yellow}brew${rf} not found"
             pprint "Installing brew..."
             /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" > $TMP_LOG_FILE 2>&1
-            if [ $? -ne 0 ]; then pprint_error "Failed to install brew"; pprint_error_info "$(cat $TMP_LOG_FILE)"; pprint_error_info "$(cat $TMP_LOG_FILE)"; exit 1; fi
+            if [ $? -ne 0 ]; then pprint_error "Failed to install brew"; pprint_error_info "$(cat $TMP_LOG_FILE)"; pprint_error_info "$(cat $TMP_LOG_FILE)"; FAILED_TASKS="$FAILED_TASKS:$TASK_NAME"; exit 1; fi
         else
             pprint_check "${green}brew${rf} found"
         fi
@@ -250,7 +255,7 @@ if [ ! -d "$HOME/.local/bin" ]; then
     pprint_warning "Directory $HOME/.local/bin not found"
     pprint "Creating directory $HOME/.local/bin..."
     mkdir -p "$HOME/.local/bin" > $TMP_LOG_FILE 2>&1
-    if [ $? -ne 0 ]; then pprint_error "Failed to create directory $HOME/.local/bin"; pprint_error_info "$(cat $TMP_LOG_FILE)"; exit 1; fi
+    if [ $? -ne 0 ]; then pprint_error "Failed to create directory $HOME/.local/bin"; pprint_error_info "$(cat $TMP_LOG_FILE)"; FAILED_TASKS="$FAILED_TASKS:$TASK_NAME"; exit 1; fi
     pprint_check "Created directory ${green}$HOME/.local/bin${rf}"
 else
     pprint "Local bin directory found"
@@ -261,7 +266,7 @@ for file in "$DOTFILES_REPO_PATH/bin/"*; do
     if [ -L "$HOME/.local/bin/$(basename "$file")" ]; then continue; fi
     pprint "Linking $file <-> $HOME/.local/bin"
     ln -sf "$file" "$HOME/.local/bin/$(basename "$file")" > $TMP_LOG_FILE 2>&1
-    if [ $? -ne 0 ]; then pprint_error "Failed to link $file to $HOME/.local/bin/$(basename "$file")"; pprint_error_info "$(cat $TMP_LOG_FILE)"; exit 1; fi
+    if [ $? -ne 0 ]; then pprint_error "Failed to link $file to $HOME/.local/bin/$(basename "$file")"; pprint_error_info "$(cat $TMP_LOG_FILE)"; FAILED_TASKS="$FAILED_TASKS:$TASK_NAME"; exit 1; fi
 done
 ##################################################
 
@@ -277,20 +282,20 @@ then
     pprint_warning "Dotfiles repository not found"
     pprint "Cloning dotfiles repository..."
     git clone --depth 1 --branch main https://github.com/irohn/dotfiles.git "$DOTFILES_REPO_PATH" > $TMP_LOG_FILE 2>&1
-    if [ $? -ne 0 ]; then pprint_error "Failed to clone dotfiles repository"; pprint_error_info "$(cat $TMP_LOG_FILE)"; exit 1; fi
+    if [ $? -ne 0 ]; then pprint_error "Failed to clone dotfiles repository"; pprint_error_info "$(cat $TMP_LOG_FILE)"; FAILED_TASKS="$FAILED_TASKS:$TASK_NAME"; exit 1; fi
     pprint_check "Dotfiles repository cloned"
 else
     pprint "Dotfiles repository is present"
     # Check if dotfiles repository is up to date
     cd "$DOTFILES_REPO_PATH"
     git fetch --depth 1 origin > $TMP_LOG_FILE 2>&1
-    if [ $? -ne 0 ]; then pprint_error "Failed to fetch dotfiles repository"; pprint_error_info "$(cat $TMP_LOG_FILE)"; exit 1; fi
+    if [ $? -ne 0 ]; then pprint_error "Failed to fetch dotfiles repository"; pprint_error_info "$(cat $TMP_LOG_FILE)"; FAILED_TASKS="$FAILED_TASKS:$TASK_NAME"; exit 1; fi
     if [ "$(git rev-parse HEAD)" != "$(git rev-parse @{u})" ]
     then
         pprint_warning "Dotfiles repository is not up to date"
         pprint "Pulling latest changes..."
         git pull > $TMP_LOG_FILE 2>&1
-        if [ $? -ne 0 ]; then pprint_error "Failed to pull dotfiles repository"; pprint_error_info "$(cat $TMP_LOG_FILE)"; exit 1; fi
+        if [ $? -ne 0 ]; then pprint_error "Failed to pull dotfiles repository"; pprint_error_info "$(cat $TMP_LOG_FILE)"; FAILED_TASKS="$FAILED_TASKS:$TASK_NAME"; exit 1; fi
         pprint_check "Dotfiles repository is up to date"
     else
         pprint_check "Dotfiles repository is up to date"
@@ -306,6 +311,7 @@ TASK_NAME="vault"
 
 if $SKIP_AUTH; then
     pprint_skip "Skipping vault related tasks"
+    SKIPPED_TASKS="$SKIPPED_TASKS:$TASK_NAME"
 else
     if ! command -v vlt > $TMP_LOG_FILE 2>&1
     then
@@ -326,7 +332,7 @@ else
         if [ $? -ne 0 ]; then
             pprint_error "Failed to download vlt"
             pprint_error_info "$(cat $TMP_LOG_FILE)"
-            exit 1
+            FAILED_TASKS="$FAILED_TASKS:$TASK_NAME"; FAILED_TASKS="$FAILED_TASKS:$TASK_NAME"; exit 1
         else
             pprint_check "vlt downloaded"
         fi
@@ -335,7 +341,7 @@ else
         if [ $? -ne 0 ]; then
             pprint_error "Failed to install vlt"
             pprint_error_info "$(cat $TMP_LOG_FILE)"
-            exit 1
+            FAILED_TASKS="$FAILED_TASKS:$TASK_NAME"; FAILED_TASKS="$FAILED_TASKS:$TASK_NAME"; exit 1
         else
             rm /tmp/vlt.zip > $TMP_LOG_FILE 2>&1
             pprint_check "vlt installed"
@@ -344,7 +350,7 @@ else
             pprint_error "Failed to install vlt"
             pprint_error_info "To install manually go to"
             pprint_error_info "${underline}${blue}https://developer.hashicorp.com/vault/tutorials/hcp-vault-secrets-get-started/hcp-vault-secrets-install-cli${rf}"
-            exit 1
+            FAILED_TASKS="$FAILED_TASKS:$TASK_NAME"; exit 1
         else
             pprint_check "${green}vlt${rf} installed"
         fi
@@ -353,49 +359,49 @@ else
     fi
     if [ ! -f "$HCP_CREDS_PATH" ]; then
         pprint_error "Credentials file $HCP_CREDS_PATH not found"
-        exit 1
+        FAILED_TASKS="$FAILED_TASKS:$TASK_NAME"; exit 1
     fi
     if [ "$(stat -c "%a" "$HCP_CREDS_PATH")" != "660" ]; then
         pprint_error "HCP client credentials file has incorrect permissions"
         pprint_error_info "Please run: ${yellow}chmod 660 $HCP_CREDS_PATH${rf}"
-        exit 1
+        FAILED_TASKS="$FAILED_TASKS:$TASK_NAME"; exit 1
     fi
     # Set environment variables from HCP secret files, using export so they are available to child processes
     export HCP_CLIENT_ID=$(jq -r '.client_id' "$HCP_CREDS_PATH")
     if [ -z "$HCP_CLIENT_ID" ]; then
         pprint_error "HCP client ID is empty"
-        exit 1
+        FAILED_TASKS="$FAILED_TASKS:$TASK_NAME"; exit 1
     fi
 
     export HCP_CLIENT_SECRET=$(jq -r '.client_secret' "$HCP_CREDS_PATH")
     if [ -z "$HCP_CLIENT_SECRET" ]; then
         pprint_error "HCP client secret is empty"
-        exit 1
+        FAILED_TASKS="$FAILED_TASKS:$TASK_NAME"; exit 1
     fi
 
     export HCP_ORGANIZATION=$(jq -r '.organization' "$HCP_CREDS_PATH")
     if [ -z "$HCP_ORGANIZATION" ]; then
         pprint_error "HCP organization is empty"
-        exit 1
+        FAILED_TASKS="$FAILED_TASKS:$TASK_NAME"; exit 1
     fi
 
     export HCP_PROJECT=$(jq -r '.project' "$HCP_CREDS_PATH")
     if [ -z "$HCP_PROJECT" ]; then
         pprint_error "HCP project is empty"
-        exit 1
+        FAILED_TASKS="$FAILED_TASKS:$TASK_NAME"; exit 1
     fi
 
     export HCP_APP_NAME=$(jq -r '.app_name' "$HCP_CREDS_PATH")
     if [ -z "$HCP_APP_NAME" ]; then
         pprint_error "HCP app name is empty"
-        exit 1
+        FAILED_TASKS="$FAILED_TASKS:$TASK_NAME"; exit 1
     fi
     print_icon "${purple}$key_icon${rf}" "Logging in to vault..."
     vlt login > $TMP_LOG_FILE 2>&1
     if [ $? -ne 0 ]; then 
         pprint_error "Failed to login to vault"
         pprint_error_info "$(cat $TMP_LOG_FILE)"
-        exit 1
+        FAILED_TASKS="$FAILED_TASKS:$TASK_NAME"; exit 1
     fi
     get_secret_from_vault() {
         vlt secrets get --organization "$HCP_ORGANIZATION" --project "$HCP_PROJECT" --app-name "$HCP_APP_NAME" --plaintext "$1"
@@ -425,13 +431,13 @@ if [ -d "$HOME/.oh-my-zsh" ]; then
 else
     # Install oh-my-zsh
     sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended > $TMP_LOG_FILE 2>&1
-    if [ $? -ne 0 ]; then pprint_error "Failed to install oh-my-zsh"; pprint_error_info "$(cat $TMP_LOG_FILE)"; exit 1; fi
+    if [ $? -ne 0 ]; then pprint_error "Failed to install oh-my-zsh"; pprint_error_info "$(cat $TMP_LOG_FILE)"; FAILED_TASKS="$FAILED_TASKS:$TASK_NAME"; exit 1; fi
 fi
 
 # Verify $HOME/.local/bin exists
 if [ ! -d "$HOME/.local/bin" ]; then
     mkdir -p "$HOME/.local/bin" > $TMP_LOG_FILE 2>&1
-    if [ $? -ne 0 ]; then pprint_error "Failed to create directory $HOME/.local/bin"; pprint_error_info "$(cat $TMP_LOG_FILE)"; exit 1; fi
+    if [ $? -ne 0 ]; then pprint_error "Failed to create directory $HOME/.local/bin"; pprint_error_info "$(cat $TMP_LOG_FILE)"; FAILED_TASKS="$FAILED_TASKS:$TASK_NAME"; exit 1; fi
 fi
 
 # Add $HOME/.local/bin to PATH
@@ -444,7 +450,7 @@ fi
 # Check if starship is already installed
 if ! command -v starship > $TMP_LOG_FILE 2>&1; then
     curl -sS https://starship.rs/install.sh | sh -s -- -y --bin-dir $HOME/.local/bin > $TMP_LOG_FILE 2>&1
-    if [ $? -ne 0 ]; then pprint_error "Failed to install starship"; pprint_error_info "$(cat $TMP_LOG_FILE)"; exit 1; fi
+    if [ $? -ne 0 ]; then pprint_error "Failed to install starship"; pprint_error_info "$(cat $TMP_LOG_FILE)"; FAILED_TASKS="$FAILED_TASKS:$TASK_NAME"; exit 1; fi
     # Make sure we eval starship in .zshrc and at the end of the file
     if ! grep -q "starship init zsh" "$HOME/".zshrc; then
         printf 'eval "$(starship init zsh)"\n' >> "$HOME/".zshrc
@@ -461,7 +467,7 @@ fi
 
 # Copy starship into XDG_CONFIG_HOME
     /bin/cp -rf "$DOTFILES_REPO_PATH"/apps/starship/starship.toml "$XDG_CONFIG_HOME"/starship.toml > $TMP_LOG_FILE 2>&1
-    if [ $? -ne 0 ]; then pprint_error "Failed to copy starship.toml"; pprint_error_info "$(cat $TMP_LOG_FILE)"; exit 1; fi
+    if [ $? -ne 0 ]; then pprint_error "Failed to copy starship.toml"; pprint_error_info "$(cat $TMP_LOG_FILE)"; FAILED_TASKS="$FAILED_TASKS:$TASK_NAME"; exit 1; fi
     pprint_check "Copied starship.toml to $XDG_CONFIG_HOME"
 ##################################################
 
@@ -487,8 +493,36 @@ if [ -d "$XDG_CONFIG_HOME/tmux/plugins/tpm" ]; then
     pprint "tmux plugin manager already installed"
 else
     # Install tmux plugin manager
-    git clone https://github.com/tmux-plugins/tpm "$XDG_CONFIG_HOME/tmux/plugins/tpm"
-    if [ $? -ne 0 ]; then pprint_error "Failed to install tmux plugin manager"; pprint_error_info "$(cat $TMP_LOG_FILE)"; exit 1; fi
+    git clone https://github.com/tmux-plugins/tpm "$XDG_CONFIG_HOME/tmux/plugins/tpm" > $TMP_LOG_FILE 2>&1
+    if [ $? -ne 0 ]; then pprint_error "Failed to install tmux plugin manager"; pprint_error_info "$(cat $TMP_LOG_FILE)"; FAILED_TASKS="$FAILED_TASKS:$TASK_NAME"; exit 1; fi
+    pprint_check "tmux plugin manager installed"
 fi
 
+# Copy tmux config into XDG_CONFIG_HOME
+/bin/cp -rf "$DOTFILES_REPO_PATH"/apps/tmux/tmux.conf "$XDG_CONFIG_HOME"/tmux/tmux.conf > $TMP_LOG_FILE 2>&1
+if [ $? -ne 0 ]; then pprint_error "Failed to copy tmux.conf"; pprint_error_info "$(cat $TMP_LOG_FILE)"; FAILED_TASKS="$FAILED_TASKS:$TASK_NAME"; exit 1; fi
+pprint_check "Copied tmux.conf to $XDG_CONFIG_HOME"
+##################################################
+
+
+
+##################################################
+#                     NEOVIM                     #
+TASK_NAME="nvim"
+
+# Check if neovim already installed
+if ! command -v nvim > $TMP_LOG_FILE 2>&1
+then
+    pprint_warning "${yellow}nvim${rf} not found"
+    pprint "Installing neovim..."
+    install_with_package_manager neovim
+    pprint_check "${green}neovim${rf} installed"
+else
+    pprint_check "${green}neovim${rf} found"
+fi
+
+# Copy neovim config from apps
+/bin/cp -rf "$DOTFILES_REPO_PATH"/apps/nvim "$XDG_CONFIG_HOME"/nvim > $TMP_LOG_FILE 2>&1
+if [ $? -ne 0 ]; then pprint_error "Failed to copy neovim config"; pprint_error_info "$(cat $TMP_LOG_FILE)"; FAILED_TASKS="$FAILED_TASKS:$TASK_NAME"; exit 1; fi
+pprint_check "Copied neovim config to $XDG_CONFIG_HOME"
 ##################################################
